package view;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.Pagamento;
import models.Credito;
import models.Debito;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author renata
 */
public class TelaPagamento extends javax.swing.JFrame {

    Pagamento pag = new Pagamento();
    private static JPanel contentPane = new JPanel();
    
    public TelaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPagamento = new javax.swing.JLabel();
        jLabelValorPagar = new javax.swing.JLabel();
        jLabelFormaPagar = new javax.swing.JLabel();
        jButtonDinheiro = new javax.swing.JButton();
        jButtonCredito = new javax.swing.JButton();
        jLabelShowValorPagar = new javax.swing.JLabel();
        jButtonDebito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPagamento.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelPagamento.setText("Pagamento");

        jLabelValorPagar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelValorPagar.setText("Valor à Pagar");

        jLabelFormaPagar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelFormaPagar.setText("Formas de Pagamento");

        jButtonDinheiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonDinheiro.setText("Dinheiro");
        jButtonDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDinheiroActionPerformed(evt);
            }
        });

        jButtonCredito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCredito.setText("Crédito");
        jButtonCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditoActionPerformed(evt);
            }
        });

        jLabelShowValorPagar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelShowValorPagar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelShowValorPagarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButtonDebito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonDebito.setText("Débito");
        jButtonDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDebitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelValorPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelShowValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFormaPagar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDinheiro)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDebito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jButtonCredito))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabelPagamento)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelPagamento)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorPagar)
                    .addComponent(jLabelShowValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabelFormaPagar)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDinheiro)
                    .addComponent(jButtonCredito)
                    .addComponent(jButtonDebito))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDinheiroActionPerformed
        String valor;
        valor = JOptionPane.showInputDialog(contentPane, "Valor à Pagar: "+pag.getTotal(), "Dinheiro", DISPOSE_ON_CLOSE);
        double numV = Double.parseDouble(valor);
        if(numV >= 0.0){
        JOptionPane.showMessageDialog(contentPane, "Valor Pago:"+pag.calcularTroco(numV, pag.getTotal()), "Confirmação de Pagamento", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDinheiroActionPerformed

    private void jButtonCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditoActionPerformed
        int num;
        String parcela;
        Credito cred = new Credito();
        JOptionPane.showMessageDialog(contentPane,"Valor à Pagar: " +pag.getTotal(), "Crédito", HEIGHT);
        cred.setTotal(pag.getTotal());
        parcela = JOptionPane.showInputDialog(contentPane, "Quantidade de Parcelas: ", "Crédito", DISPOSE_ON_CLOSE);
        num = Integer.parseInt(parcela);
        JOptionPane.showMessageDialog(contentPane,"Valor Parcela: " +cred.pagarCredito(num, cred.getTotal()) + "\nNovo Limite: "+cred.getLimite(), "Crédito", HEIGHT);
        
    }//GEN-LAST:event_jButtonCreditoActionPerformed

    private void jLabelShowValorPagarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelShowValorPagarAncestorAdded
        pag.setTotal(Double.parseDouble(this.subtotal.getText()));
        this.jLabelShowValorPagar.setText(String.valueOf(pag.getTotal()));
        
    }//GEN-LAST:event_jLabelShowValorPagarAncestorAdded

    private void jButtonDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDebitoActionPerformed

        Debito deb = new Debito();
        JOptionPane.showMessageDialog(contentPane,"Valor à Pagar: " +pag.getTotal(), "Débito", HEIGHT);
        deb.setTotal(pag.getTotal());
    }//GEN-LAST:event_jButtonDebitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    JLabel subtotal;
    public TelaPagamento(JLabel lblSubtotal) {
        initComponents();
        this.subtotal = lblSubtotal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCredito;
    private javax.swing.JButton jButtonDebito;
    private javax.swing.JButton jButtonDinheiro;
    private javax.swing.JLabel jLabelFormaPagar;
    private javax.swing.JLabel jLabelPagamento;
    private javax.swing.JLabel jLabelShowValorPagar;
    private javax.swing.JLabel jLabelValorPagar;
    // End of variables declaration//GEN-END:variables
}
